version: '3.8'
services:
  dmit_facturador_landing_page:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dmit_facturador_landing_page
    restart: always
    ports:
      - "3000:3000"
    networks:
      - dmit_network

networks:
  dmit_network:
    external: true
