version: '3.1'
services:
  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_app
    image: web_app
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl-certificates:/etc/letsencrypt
